version: '3.4'

services:
  pokemon.api:
    build:
      context: .
      dockerfile: src/PokemonTranslator.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      